# .github/workflows/sync-readme.yml
name: Sync README from private SAGE

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout private SAGE repo
        uses: actions/checkout@v3
        with:
          repository: intellistream/SAGE
          token: ${{ secrets.SAGE_REPO_TOKEN }}
          path: SAGE

      - name: Copy README
        run: |
          cp SAGE/README.md docs_src/about.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs_src/about.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "sync: update about.md from SAGE README"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-readme
          title: "sync: update about.md from SAGE README"
          body: |
            This PR was automatically generated by sync‐readme.yml.
            It updates docs_src/about.md with the latest SAGE README.
          base: main
          labels: automated-sync
